name: sunshine
description: Sunshine DAO frontend
version: 1.0.0+1
environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  cupertino_icons: ^0.1.2
  flutter:
    sdk: flutter
  flutter_svg: ^0.17.4
  keystore:
    path: packages/keystore_ffi
  path_provider: ^1.6.5
  flutter_screenutil: ^1.1.0
  provider: ^4.1.0
  injectable: ^0.3.0
  get_it: ^4.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.8.0
  injectable_generator: ^0.3.5
  build_runner: ^1.9.0

flutter:
  uses-material-design: true
  assets:
    - assets/
