name: sunshine
description: Sunshine DAO frontend
version: 1.0.0+1
environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  bloc: ^3.0.0
  fluid_layout: ^0.1.0
  flutter:
    sdk: flutter
  flutter_bloc: ^3.1.0
  flutter_svg: ^0.17.4
  keystore:
    path: ../keystore/keystore-dart

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.3.0

flutter:
  assets:
  - assets/

  fonts:
  - family: Roboto
    fonts:
    - asset: assets/fonts/Roboto-Regular.ttf
  - family: MaterialIcons
    fonts:
    - asset: assets/fonts/MaterialIcons-Regular.ttf
