on: [push, pull_request]

name: (Android, iOS)

jobs:
  ci:
    name: Compile, Build and Release
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Cache LLVM and Clang
        id: cache-llvm
        uses: actions/cache@v2
        with:
          path: ${{ runner.temp }}/llvm/10.0
          key: ${{ runner.os }}-cached-llvm-10.0

      - name: Install LLVM and Clang
        uses: KyleMayes/install-llvm-action@v1
        with:
          version: "10.0"
          directory: ${{ runner.temp }}/llvm/10.0
          cached: ${{ steps.cache-llvm.outputs.cache-hit }}

      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install Rust Toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
          components: rustfmt

      - name: Install WASM Target
        run: rustup target add wasm32-unknown-unknown

      - name: Cache Cargo
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            ~/.cargo/bin
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Install Cargo Tools (cargo-make, cbindgen, dart-bindgen)
        uses: actions-rs/cargo@v1
        continue-on-error: true
        with:
          command: install
          args: cargo-make cbindgen dart-bindgen

      - name: Setup Flutter
        uses: subosito/flutter-action@v1
        with:
          channel: "stable"

      - name: Run Flutter pub get
        run: flutter pub get

      - name: Set up JDK 1.8 (Android only)
        uses: actions/setup-java@v1
        if: matrix.os == 'ubuntu-latest'
        with:
          java-version: 1.8

      - name: Setup Android SDK (Android only)
        if: matrix.os == 'ubuntu-latest'
        uses: android-actions/setup-android@v1

      - name: Cache NDK (Android only)
        if: matrix.os == 'ubuntu-latest'
        id: cache-ndk
        uses: actions/cache@v2
        with:
          path: /home/runner/android/ndk-bundle
          key: ${{ runner.os }}-ndk

      - name: Install Android NDK (Android only)
        if: steps.cache-ndk.outputs.cache-hit != 'true' && matrix.os == 'ubuntu-latest'
        run: $ANDROID_SDK_ROOT/tools/bin/sdkmanager ndk-bundle

      - name: Set Android NDK Env (Android only)
        if: matrix.os == 'ubuntu-latest'
        run: echo '::set-env name=ANDROID_NDK_HOME::/home/runner/android/ndk-bundle'

      - name: Install Android Targets (Android only)
        if: matrix.os == 'ubuntu-latest'
        run: rustup target add aarch64-linux-android armv7-linux-androideabi x86_64-linux-android i686-linux-android

      - name: Run cargo make android (Release)
        if: matrix.os == 'ubuntu-latest'
        uses: actions-rs/cargo@v1
        continue-on-error: false
        with:
          command: make
          args: android --profile release

      - name: Build APK (Fat)
        if: matrix.os == 'ubuntu-latest'
        run: flutter build apk --debug

      - name: Install iOS Targets (iOS only)
        if: matrix.os == 'macos-latest'
        run: rustup target add aarch64-apple-ios x86_64-apple-ios

      - name: Run cargo make ios (Release)
        if: matrix.os == 'macos-latest'
        uses: actions-rs/cargo@v1
        continue-on-error: false
        with:
          command: make
          args: ios --profile release

      - name: Build iOS App (Simulator, Debug)
        if: matrix.os == 'macos-latest'
        run: flutter build ios --debug --no-codesign --simulator

      - name: Build APK (arm64, Release)
        if: matrix.os == 'ubuntu-latest'
        run: |
          rm -f packages/sunshine/android/src/main/jniLibs/x86_64/libsunshine.so
          rm -f packages/sunshine/android/src/main/jniLibs/x86/libsunshine.so
          rm -f packages/sunshine/android/src/main/jniLibs/armeabi-v7a/libsunshine.so
          flutter build apk --release --target-platform android-arm64

      - name: Create Release (Android)
        id: create_release
        if: matrix.os == 'ubuntu-latest'
        uses: ChanTsune/release-with-commit@v1.0.0
        with:
          regexp: "Release (\\d+([.]\\d+)*)\n*((\\s|\\S)+)"
          regexp_options: "us"
          release_name: "version $1"
          tag_name: "v$1"
          body: "$3"
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Release (Android)
        id: upload-release-asset
        if: matrix.os == 'ubuntu-latest' && steps.create_release.outputs.upload_url != null
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./build/app/outputs/flutter-apk/app-release.apk
          asset_name: sunshine-release-arm64.apk
          asset_content_type: application/octet-stream
